version: '3'

services:

  property_me_be:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start:dev
    container_name: property_me_be_container
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8070:3000'
    depends_on:
      - property_db
    environment:
      DB_URL: mysql://root:12345678@property_db_container:3306/property_me
      DB_DRIVER: mysql

# mysql -h 0.0.0.0 -P 3390 -u root -D property_me -p'12345678' // to connect mysql from terminal
  property_db:
    # platform: linux/x86_64 // for mac m1 build
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: property_me
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: property_db_container
    ports:
      - '3390:3306'
  
